#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER p6 WITH ENCRYPTED PASSWORD 'p6';
    CREATE DATABASE p6;
    GRANT ALL PRIVILEGES ON DATABASE p6 TO p6;
EOSQL
